# <% branch_name = `git symbolic-ref HEAD 2>/dev/null`.chomp.sub('refs/heads/', '') %>
# <% repository_name = `git rev-parse --show-toplevel`.split('/').last.strip %>

development:
  adapter: postgresql
  encoding: unicode
  database: dev_development
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: dev_test
  pool: 5
  username: postgres
  password: postgres
